/* "import "redux"" is auto-generated by Snack after importing from "react-redux" */
import "redux" // 3.7.2
// @TO-DO: Delete above after Snack fix this bug

import React, { Component } from 'react'
import { View, StyleSheet } from 'react-native'
import { Provider } from 'react-redux' // 5.0.6
import { Constants } from 'expo'

import store from './src/state/Store'
import { RootNavigator } from './src/navigation'

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <View style={styles.container}>
          <RootNavigator />
        </View>
      </Provider>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Constants.statusBarHeight,
  },
})